on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push the image to Amazon ECR
      run: |
        # Get current UTC time as image tag
        IMAGE_TAG=$(date -u +"%Y%m%dT%H%M%SZ")
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

        # Build a Docker container and push it to ECR
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_NAME }}:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_NAME }}:$IMAGE_TAG
        echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_NAME }}:$IMAGE_TAG"
      env:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_REGION: ap-northeast-2
